debug: false

spring:
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver